site_name: Game Programming - Portfolio
pages:
- Home: index.md
- University Projects: universityprojects.md
- Self Learning: selflearning.md
- Past Projects: pastprojects.md
- Résumé: resume.md
theme: cinder