site_name: Game Programming - Portfolio
pages:
- Home: index.md
- LevelManager: levelmanager.md
- AudioManager: audiomanager.md
- ArtificalIntelligence: artificialintelligence.md
- PastProjects: pastprojects.md
theme: cinder